name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - opencv
  - pip
  - pip:
    - streamlit
    - ultralytics
    - streamlit-webrtc
    - av
    - twilio
    - openpyxl
    - Pillow
    - numpy
